create database getbank
;
use getbank
;
CREATE TABLE KLANTGEGEVENS(
KLANTID SMALLINT PRIMARY KEY,
REKENINGNUMMER CHAR(18) NOT NULL,
VOORNAAM CHAR(35) NOT NULL,
ACHTERNAAM CHAR(35) NOT NULL,
GEBOORTEDATUM DATE NOT NULL,
ADRES CHAR(50) NOT NULL,
WOONPLAATS CHAR(35) NOT NULL,
POSTCODE CHAR(7) NOT NULL,
GESLACHT CHAR(1) NOT NULL,
TELEFOONNR CHAR(12) NOT NULL,
EMAILADRES CHAR(50) NOT NULL)
;
CREATE TABLE REKENINGEN(
REKENINGNUMMER CHAR(18) PRIMARY KEY,
KLANTID SMALLINT NOT NULL,
SALDO INTEGER,
PINCODE SMALLINT NOT NULL,
INLOGPOGINGEN TINYINT(1) DEFAULT 0)
;
